name: Build Docker Image

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 9090:9090
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Build and push to local registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mytag:latest
